project_id = "eewyqxhntjzrouixpxpr"

[functions.record-crypto-tip]
verify_jwt = false

[functions.create-stripe-payment]
verify_jwt = false

[functions.update-tip-status]
verify_jwt = false

[functions.stripe-config]
verify_jwt = false