project_id = "eewyqxhntjzrouixpxpr"

[functions.record-crypto-tip]
verify_jwt = false

[functions.create-stripe-payment]
verify_jwt = false

[functions.update-tip-status]
verify_jwt = false

[functions.stripe-config]
verify_jwt = false

[functions.send-invitation]
verify_jwt = true

[functions.resolve-invitation]
verify_jwt = false

[functions.accept-invitation]
verify_jwt = true

[functions.finalize-server-signup]
verify_jwt = true

[functions.finalize-owner-signup]
verify_jwt = true

[functions.calculate-venue-metrics]
verify_jwt = false
